### ISSUE TITLE
Bad filename

### ISSUE THREAD

**Issue by cbevington** [dfujim/SpreadsheetPlagiarism#10]
This might be impossible to workaround; the student has "~$" in the filename which throws an OS error when opening. If I rename the file I'm guessing this alters the metadata and makes the comparison useless? Below is the full traceback and the attached spreadsheet:

Traceback (most recent call last):
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/reader/excel.py", line 121, in _validate_archive
    archive = ZipFile(filename, 'r', ZIP_DEFLATED)
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/comparer.py", line 481, in load
    self.book2 = openpyxl.load_workbook(self.file2)
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/reader/excel.py", line 174, in load_workbook
    archive = _validate_archive(filename)
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/reader/excel.py", line 124, in _validate_archive
    archive = ZipFile(f, 'r', ZIP_DEFLATED)
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/__main__.py", line 119, in <module>
    c.compare(options=args.options,do_print=args.full,do_verbose=args.verbose)
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/multifile_comparer.py", line 223, in compare
    self._compare(map,cm,do_verbose)
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/multifile_comparer.py", line 196, in _compare
    for i,c in tqdm(enumerate(mapfn(compare_fn,self.comparers)),total=ncompare):
  File "/home/connor/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 1002, in __iter__
    for obj in iterable:
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/multifile_comparer.py", line 507, in do_compare
    c.compare(options=options,do_print=do_print)
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/comparer.py", line 343, in compare
    self.load()
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/comparer.py", line 483, in load
    raise OSError('Unable to open %s.' % self.file2)
OSError: Unable to open ./peng_jiayan117990_question_1081090_3743665_~$Physics Pre-lab 02.xlsx.
[peng_jiayan117990_question_1081090_3743665_~$Physics Pre-lab 02.xlsx](https://github.com/dfujim/SpreadsheetPlagiarism/files/2785774/peng_jiayan117990_question_1081090_3743665_.Physics.Pre-lab.02.xlsx)

**Comment by dfujim** [comment]
This doesn't seem to be a character issue, at least not for the filename. It might be a font family thing again, or perhaps some other issue. Opening the file in LibreOffice shows that the text needs to be imported.

**Comment by dfujim** [comment]
Removed attached file due to privacy issues.
