### ISSUE TITLE
Font family exceeds max value

### ISSUE THREAD

**Issue by cbevington** [dfujim/SpreadsheetPlagiarism#11]
This student has appeared to change font.family > 14, which throws the error. It looks to be some sort of Asian language font. Traceback and file are attached below:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/__main__.py", line 119, in <module>
    c.compare(options=args.options,do_print=args.full,do_verbose=args.verbose)
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/multifile_comparer.py", line 223, in compare
    self._compare(map,cm,do_verbose)
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/multifile_comparer.py", line 196, in _compare
    for i,c in tqdm(enumerate(mapfn(compare_fn,self.comparers)),total=ncompare):
  File "/home/connor/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 1002, in __iter__
    for obj in iterable:
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/multifile_comparer.py", line 507, in do_compare
    c.compare(options=options,do_print=do_print)
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/comparer.py", line 343, in compare
    self.load()
  File "/home/connor/.local/lib/python3.5/site-packages/compsheet/comparer.py", line 481, in load
    self.book2 = openpyxl.load_workbook(self.file2)
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/reader/excel.py", line 223, in load_workbook
    apply_stylesheet(archive, wb) # bind styles to workbook
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/styles/stylesheet.py", line 178, in apply_stylesheet
    stylesheet = Stylesheet.from_tree(node)
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/styles/stylesheet.py", line 100, in from_tree
    return super(Stylesheet, cls).from_tree(node)
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/descriptors/serialisable.py", line 80, in from_tree
    obj = desc.from_tree(el)
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/descriptors/sequence.py", line 86, in from_tree
    return [self.expected_type.from_tree(el) for el in node]
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/descriptors/sequence.py", line 86, in <listcomp>
    return [self.expected_type.from_tree(el) for el in node]
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/styles/fonts.py", line 110, in from_tree
    return super(Font, cls).from_tree(node)
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/descriptors/serialisable.py", line 100, in from_tree
    return cls(**attrib)
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/styles/fonts.py", line 76, in __init__
    self.family = family
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/descriptors/nested.py", line 36, in __set__
    super(Nested, self).__set__(instance, value)
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/descriptors/base.py", line 110, in __set__
    super(Min, self).__set__(instance, value)
  File "/home/connor/.local/lib/python3.5/site-packages/openpyxl/descriptors/base.py", line 89, in __set__
    raise ValueError('Max value is {0}'.format(self.max))
ValueError: Max value is 14

**Comment by dfujim** [comment]
This is an issue with loading the file, it exists in openpyxl. For now the solution appears to be: Open the file in excel (or similar) and change the font. 

Here's the [bug report for openpyxl](https://bitbucket.org/openpyxl/openpyxl/issues/373/fontfamily-of-34-prevents-load).

**Comment by dfujim** [comment]
Removed attached files due to privacy issues.

**Comment by mfripp** [comment]
I had the same error in openpyxl 3.0.0 with an xlsx file saved from Excel for Mac 16.40 (Office 365). I fixed the problem by opening the file in Excel, saving as .xls (Excel 97-2004), then opening that and re-saving as .xlsx. Upgrading openpyxl might have helped too (3.0.4 is the latest currently available).
